/*
 * Peace✘ - Discord Bot
 * Developed by Smith.Code
 *
 * Loads play-dl credentials (YouTube cookies, optional Spotify & SoundCloud
 * tokens) so streaming works. YouTube started gating stream URL delivery on
 * cookies/PO-tokens, so `playdl.stream()` returns empty `format[].url` without
 * them (that was the "Invalid URL" crash). Pasted here, all YouTube sources
 * stream normally again.
 *
 * Accepted sources (first found wins):
 *   1. <repo>/cookies.json   -> flexible JSON (see README in file)
 *   2. <repo>/.data/youtube.data (play-dl's native cookie dump)
 *
 * cookies.json shape:
 *   {
 *     "youtube": "VISITOR_INFO1_LIVE=...; __Secure-...=...; ...", // cookie header string
 *     // or
 *     "youtube": { "cookie": { "name": "value", ... } },
 *     "spotify": { "client_id": "...", "client_secret": "...", "redirect_url": "...", "authorization_code": "..." },
 *     "soundcloud": "client_id_string"
 *   }
 */
const fs = require('fs');
const path = require('path');
const playdl = require('play-dl');

const ROOT = path.join(__dirname, '..', '..');

/** Parse a "a=b; c=d" cookie header into { a:'b', c:'d' }. */
function cookieStringToObject(str) {
  const out = {};
  for (const part of String(str).split(';')) {
    const idx = part.indexOf('=');
    if (idx === -1) continue;
    const k = part.slice(0, idx).trim();
    const v = part.slice(idx + 1).trim();
    if (k) out[k] = v;
  }
  return out;
}

/** Normalise the youtube cookie source into { name: value } object. */
function resolveYoutubeCookie(cfg) {
  if (!cfg) return null;
  // native play-dl dump: { "youtube": { "cookie": {...} } }
  if (cfg.cookie && typeof cfg.cookie === 'object' && !Array.isArray(cfg.cookie)) {
    return cfg.cookie;
  }
  // cookie header string
  if (typeof cfg === 'string') {
    const obj = cookieStringToObject(cfg);
    return Object.keys(obj).length ? obj : null;
  }
  // plain object of cookie pairs
  if (typeof cfg === 'object') {
    const hasReal = Object.keys(cfg).some((k) => /CONSENT|VISITOR|__Secure|LOGIN_INFO|SID|SAPISID|HSID|SSID|APISID/i.test(k));
    if (hasReal || Object.keys(cfg).length) return cfg;
  }
  return null;
}

function loadFromJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

/** Serialise a cookie object into a "a=b; c=d" header string (play-dl expects a string). */
function cookieObjectToString(obj) {
  return Object.entries(obj)
    .map(([k, v]) => `${k}=${v}`)
    .join('; ');
}

/**
 * Write a Netscape-format cookies.txt (for yt-dlp) from a cookie object.
 * yt-dlp streams via --cookies <file>; this keeps it in sync with the same
 * session loaded into play-dl. Refreshes whenever applyCredentials runs.
 */
function writeNetscapeCookies(cookieObj, file = path.join(ROOT, 'cookies.txt')) {
  try {
    const lines = ['# Netscape HTTP Cookie File', '# This file is generated by PeaceX (dlconf).', ''];
    for (const [k, v] of Object.entries(cookieObj)) {
      lines.push(`.youtube.com\tTRUE\t/\tTRUE\t0\t${k}\t${v}`);
    }
    fs.writeFileSync(file, lines.join('\n'));
  } catch {
    // non-fatal; yt-dlp will just be launched without cookies
  }
}

/**
 * Apply whatever credentials are available. Returns a summary string for logs.
 */
async function applyCredentials() {
  const applied = [];

  // 1. cookies.json
  const jsonFiles = [path.join(ROOT, 'cookies.json'), path.join(ROOT, '.data', 'cookies.json')];
  let jsonCfg = null;
  for (const f of jsonFiles) {
    if (fs.existsSync(f)) {
      jsonCfg = loadFromJson(f);
      if (jsonCfg) break;
    }
  }

  // 2. play-dl native dump: .data/youtube.data
  let nativeYt = null;
  const nativePath = path.join(ROOT, '.data', 'youtube.data');
  if (fs.existsSync(nativePath)) {
    nativeYt = loadFromJson(nativePath);
  }

  // ── YouTube ────────────────────────────────────────────────────────
  // play-dl's setToken wants a cookie HEADER STRING ("a=b; c=d"). Normalise
  // whatever we found (string, {cookie:{...}}, or {name:value}) into one.
  const ytCookieObj = resolveYoutubeCookie(jsonCfg?.youtube) || resolveYoutubeCookie(nativeYt);
  if (ytCookieObj && Object.keys(ytCookieObj).length) {
    const header = cookieObjectToString(ytCookieObj);
    // play-dl (search/metadata) still uses a cookie header string.
    await playdl.setToken({ youtube: { cookie: header } }).catch(() => {});
    // yt-dlp (streaming) needs a Netscape-format cookies file.
    writeNetscapeCookies(ytCookieObj);
    applied.push(`YouTube cookies (${Object.keys(ytCookieObj).length} pairs)`);
  } else {
    applied.push('YouTube cookies (⚠ none — streaming will fail)');
  }

  // ── SoundCloud ─────────────────────────────────────────────────────
  const sc = jsonCfg?.soundcloud || jsonCfg?.soundCloud;
  if (sc && typeof sc === 'string') {
    await playdl.setToken({ soundcloud: sc }).catch(() => {});
    applied.push('SoundCloud token');
  }

  // ── Spotify ────────────────────────────────────────────────────────
  // The source of truth is .data/spotify.data — play-dl loads it at require
  // time, so `playdl.spotify()` works once that file exists. Generate it once
  // by running `npm run spotify`. Do NOT rely on cookies.json's single-use
  // authorization_code (it is consumed on first exchange and breaks on restart).
  const spotDataFile = path.join(ROOT, '.data', 'spotify.data');
  const sp = jsonCfg?.spotify;
  if (fs.existsSync(spotDataFile)) {
    applied.push('Spotify token (.data/spotify.data)');
  } else if (sp && sp.client_id && sp.client_secret) {
    applied.push('Spotify: run `npm run spotify` once to authorize');
  }

  return applied;
}

module.exports = { applyCredentials, cookieStringToObject, resolveYoutubeCookie, writeNetscapeCookies };
